
package proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yosbiel A
 */
public class FrmPrincipal extends javax.swing.JFrame {
 private int idSeleccionado = -1;
 LinkedStack<String> pilaHistorial= new LinkedStack<>();
    
    public FrmPrincipal() {
      initComponents();

        cbTipo.removeAllItems();
        cbTipo.addItem("Individual");
        cbTipo.addItem("Multifamiliar");

        cbEstado.removeAllItems();
        cbEstado.addItem("Buena");
        cbEstado.addItem("Regular");
        cbEstado.addItem("Mala");

        listarViviendas();
        limpiarCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        bAgregarVivienda = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        chkDisponible = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViviendas = new javax.swing.JTable();
        bModificarVivienda = new javax.swing.JButton();
        bEliminarVivienda = new javax.swing.JButton();
        btnDeshacer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Dirección");

        jLabel3.setText("Tipo");

        jLabel4.setText("Estado");

        jLabel5.setText("Disponible");

        txtCodigo.setColumns(15);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        txtDireccion.setColumns(15);
        txtDireccion.setText("                               ");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bAgregarVivienda.setText("Agregar Vivienda");
        bAgregarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAgregarViviendaActionPerformed(evt);
            }
        });

        bSalir.setText("Atrás");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        tblViviendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Código", "Dirección", "Tipo", "Estado", "Disponible"
            }
        ));
        tblViviendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViviendasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViviendas);

        bModificarVivienda.setText("Modificar Vivienda");
        bModificarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificarViviendaActionPerformed(evt);
            }
        });

        bEliminarVivienda.setText("Eliminar Vivienda");
        bEliminarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarViviendaActionPerformed(evt);
            }
        });

        btnDeshacer.setText("Deshacer");
        btnDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(45, 45, 45)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(chkDisponible))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAgregarVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bModificarVivienda))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bEliminarVivienda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeshacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(210, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(bSalir)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(chkDisponible))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAgregarVivienda)
                    .addComponent(btnDeshacer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModificarVivienda)
                    .addComponent(bEliminarVivienda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

            
 
    private void listarViviendas() {
    DefaultTableModel modelo = (DefaultTableModel) tblViviendas.getModel();
    modelo.setRowCount(0);

    String sql = "SELECT id_vivienda, codigo, direccion, tipo, estado, disponible FROM vivienda";

    try (Connection con = ConexionBD.getConexion();
         PreparedStatement ps = con.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            Object[] fila = new Object[6];
            fila[0] = rs.getInt("id_vivienda");
            fila[1] = rs.getString("codigo");
            fila[2] = rs.getString("direccion");
            fila[3] = rs.getString("tipo");
            fila[4] = rs.getString("estado");
            fila[5] = rs.getBoolean("disponible");

            modelo.addRow(fila);
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al listar viviendas");
        e.printStackTrace();
    }

    }
        
    private void limpiarCampos() {
        txtCodigo.setText("");
        txtDireccion.setText("");
        cbTipo.setSelectedIndex(0);
        cbEstado.setSelectedIndex(0);
        chkDisponible.setSelected(false);
    }


    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void bAgregarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAgregarViviendaActionPerformed

    String codigo = txtCodigo.getText().trim();
    String direccion = txtDireccion.getText().trim();
    String tipo = cbTipo.getSelectedItem().toString();
    String estado = cbEstado.getSelectedItem().toString();
    boolean disponible = chkDisponible.isSelected();

    if (codigo.isEmpty() || direccion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Debe completar todos los campos");
        return;
    }

    try (Connection con = ConexionBD.getConexion()) {

        String validar = "SELECT COUNT(*) FROM vivienda WHERE codigo = ?";
        PreparedStatement psValidar = con.prepareStatement(validar);
        psValidar.setString(1, codigo);
        ResultSet rs = psValidar.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Ya existe una vivienda con ese código");
            return;
        }

        String sql = "INSERT INTO vivienda (codigo, direccion, tipo, estado, disponible) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);

        ps.setString(1, codigo);
        ps.setString(2, direccion);
        ps.setString(3, tipo);
        ps.setString(4, estado);
        ps.setBoolean(5, disponible);

        ps.executeUpdate();

        String sqlUndo = "DELETE FROM vivienda WHERE codigo = '" + codigo + "'";
        pilaHistorial.Push(sqlUndo);

        JOptionPane.showMessageDialog(this, "Vivienda agregada correctamente");
        listarViviendas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al agregar vivienda");
        e.printStackTrace();
    }
    }//GEN-LAST:event_bAgregarViviendaActionPerformed

    private void tblViviendasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViviendasMouseClicked
     int fila = tblViviendas.getSelectedRow();

    if (fila >= 0) {
        idSeleccionado = Integer.parseInt(
            tblViviendas.getValueAt(fila, 0).toString()
        );

        txtCodigo.setText(tblViviendas.getValueAt(fila, 1).toString());
        txtDireccion.setText(tblViviendas.getValueAt(fila, 2).toString());
        cbTipo.setSelectedItem(tblViviendas.getValueAt(fila, 3).toString());
        cbEstado.setSelectedItem(tblViviendas.getValueAt(fila, 4).toString());

        boolean disponible = (boolean) tblViviendas.getValueAt(fila, 5);
        chkDisponible.setSelected(disponible);
    }

    }//GEN-LAST:event_tblViviendasMouseClicked

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
     FrmMenuPrincipal menu = new FrmMenuPrincipal();
      menu.setVisible(true);
      this.dispose();

    }//GEN-LAST:event_bSalirActionPerformed

    private void bModificarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificarViviendaActionPerformed
     int fila = tblViviendas.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una vivienda");
        return;
    }

    String codigo = tblViviendas.getValueAt(fila, 1).toString();

    String direccionVieja = tblViviendas.getValueAt(fila, 2).toString();
    String tipoViejo = tblViviendas.getValueAt(fila, 3).toString();
    String estadoViejo = tblViviendas.getValueAt(fila, 4).toString();
    boolean disponibleViejo = Boolean.parseBoolean(tblViviendas.getValueAt(fila, 5).toString());
    
    String direccionNueva = txtDireccion.getText();
    String tipoNuevo = cbTipo.getSelectedItem().toString();
    String estadoNuevo = cbEstado.getSelectedItem().toString();
    boolean disponibleNuevo = chkDisponible.isSelected();

    String sql = "UPDATE vivienda SET direccion=?, tipo=?, estado=?, disponible=? WHERE codigo=?";

    try (Connection con = ConexionBD.getConexion();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, direccionNueva);
        ps.setString(2, tipoNuevo);
        ps.setString(3, estadoNuevo);
        ps.setBoolean(4, disponibleNuevo);
        ps.setString(5, codigo);

        ps.executeUpdate();

        String sqlUndo = "UPDATE vivienda SET direccion='"
                + direccionVieja + "', tipo='"
                + tipoViejo + "', estado='"
                + estadoViejo + "', disponible="
                + disponibleViejo
                + " WHERE codigo='" + codigo + "'";
        pilaHistorial.Push(sqlUndo);

        JOptionPane.showMessageDialog(this, "Vivienda modificada correctamente");
        listarViviendas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al modificar vivienda");
        e.printStackTrace();
    }

    }//GEN-LAST:event_bModificarViviendaActionPerformed

    private void bEliminarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarViviendaActionPerformed
  
    int fila = tblViviendas.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione una vivienda");
        return;
    }

    int id = Integer.parseInt(tblViviendas.getValueAt(fila, 0).toString());
    String codigo = tblViviendas.getValueAt(fila, 1).toString();
    String direccion = tblViviendas.getValueAt(fila, 2).toString();
    String tipo = tblViviendas.getValueAt(fila, 3).toString();
    String estado = tblViviendas.getValueAt(fila, 4).toString();
    boolean disponible = Boolean.parseBoolean(tblViviendas.getValueAt(fila, 5).toString());

    int opcion = JOptionPane.showConfirmDialog(
        this,
        "¿Está seguro de eliminar esta vivienda?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
    );

    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }

    String sql = "DELETE FROM vivienda WHERE id_vivienda = ?";

    try (Connection con = ConexionBD.getConexion();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setInt(1, id);
        ps.executeUpdate();

        String sqlUndo =
            "INSERT INTO vivienda (codigo, direccion, tipo, estado, disponible) VALUES ('"
            + codigo + "', '" + direccion + "', '" + tipo + "', '" + estado + "', " + disponible + ")";
        pilaHistorial.Push(sqlUndo);

        JOptionPane.showMessageDialog(this, "Vivienda eliminada correctamente");
        listarViviendas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar vivienda");
        e.printStackTrace();
    }

    }//GEN-LAST:event_bEliminarViviendaActionPerformed

    private void btnDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerActionPerformed

    if (pilaHistorial.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay acciones para deshacer");
        return;
    }

    String sqlUndo = pilaHistorial.Pop();

    try (Connection con = ConexionBD.getConexion();
         PreparedStatement ps = con.prepareStatement(sqlUndo)) {

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Acción deshecha correctamente");
        listarViviendas();
        limpiarCampos();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al deshacer la acción");
        e.printStackTrace();
    }

    }//GEN-LAST:event_btnDeshacerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FrmPrincipal().setVisible(true));
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregarVivienda;
    private javax.swing.JButton bEliminarVivienda;
    private javax.swing.JButton bModificarVivienda;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton btnDeshacer;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JCheckBox chkDisponible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblViviendas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    // End of variables declaration//GEN-END:variables
}